# Generated by Django 3.1.7 on 2021-03-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210331_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='link',
            new_name='urllink',
        ),
    ]
